name: Build Ultramat application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            distro: ubuntu22.04
            output_name: Ultramat.x86_64
          - arch: aarch64
            distro: bookworm
            output_name: Ultramat.aarch64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      # Native build for x86 targets
      - name: Build (native)
        if: ${{ matrix.arch == 'x86_64' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential pkg-config libgtk-3-dev meson ninja-build
          pip3 install protobuf grpcio-tools
          echo "Compiling for ${{ matrix.arch }}..."
          # Mark the current directory as safe for git
          git config --global --add safe.directory '*'
          # setup and build
          meson setup build
          meson compile -C build
          # Verify the binary format
          file build/${{ matrix.output_name }}

      # Cross build for targets that are not x86
      - name: Build (cross)
        uses: uraimo/run-on-arch-action@v2
        if: ${{ matrix.arch != 'x86_64' }}
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          # Mount the source code directory into the container
          # The action mounts the current workspace to /home/runner/work/... by default
          # Using githubToken enables caching of the docker images
          githubToken: ${{ github.token }}

          # The shell to run commands with in the container
          shell: /bin/sh

          # 1. Install Dependencies inside the container (Virtual or Native)
          install: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -q -y
            apt-get install -q -y --no-install-recommends \
              git build-essential pkg-config libgtk-3-dev cmake ninja-build python3.11-venv python3-pip

          # 2. Run the Build Command
          run: |
            echo "Compiling for ${{ matrix.arch }}..."
            # Mark the current directory as safe for git
            git config --global --add safe.directory '*'
            # TODO: Add this here until trixie is available
            python3 -m venv venv
            . ./venv/bin/activate
            pip3 install meson protobuf grpcio-tools
            # setup and build
            meson setup build
            meson compile -C build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ultramat_UI.${{ matrix.arch }}
          path: |
            build/${{ matrix.output_name }}
            res/
