name: Build Ultramat application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            os: ubuntu22.04
            output_name: Ultramat.x86_64
          - arch: aarch64
            os: ubuntu-22.04-arm
            output_name: Ultramat.aarch64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Build ${{ matrix.output_name }}
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential pkg-config libgtk-3-dev ninja-build
          # Instal meson from pip for newer version
          pip3 install protobuf grpcio-tools meson

          # Mark the current directory as safe for git
          git config --global --add safe.directory '*'
          # setup and build
          meson setup build
          meson compile -C build
          file build/${{ matrix.output_name }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ultramat_UI.${{ matrix.arch }}
          path: |
            build/${{ matrix.output_name }}
            res/
